[2023-04-11T13:03:38.875+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task manual__2023-04-11T13:03:34.558469+00:00 [queued]>
[2023-04-11T13:03:38.945+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task manual__2023-04-11T13:03:34.558469+00:00 [queued]>
[2023-04-11T13:03:38.947+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T13:03:38.950+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-11T13:03:38.952+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T13:03:39.095+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonVirtualenvOperator): joke_collector_task> on 2023-04-11 13:03:34.558469+00:00
[2023-04-11T13:03:39.119+0000] {standard_task_runner.py:55} INFO - Started process 101 to run task
[2023-04-11T13:03:39.156+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'joke_collector', 'joke_collector_task', 'manual__2023-04-11T13:03:34.558469+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_joke_collector.py', '--cfg-path', '/tmp/tmpjgzm58vb']
[2023-04-11T13:03:39.160+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask joke_collector_task
[2023-04-11T13:03:39.741+0000] {task_command.py:389} INFO - Running <TaskInstance: joke_collector.joke_collector_task manual__2023-04-11T13:03:34.558469+00:00 [running]> on host 50c06fed4afa
[2023-04-11T13:03:40.025+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=joke_collector
AIRFLOW_CTX_TASK_ID=joke_collector_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T13:03:34.558469+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-11T13:03:34.558469+00:00
[2023-04-11T13:03:40.034+0000] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv8vzl1bne --system-site-packages
[2023-04-11T13:03:40.058+0000] {process_utils.py:183} INFO - Output:
[2023-04-11T13:03:46.612+0000] {process_utils.py:187} INFO - created virtual environment CPython3.7.16.final.0-64 in 3239ms
[2023-04-11T13:03:46.614+0000] {process_utils.py:187} INFO -   creator CPython3Posix(dest=/tmp/venv8vzl1bne, clear=False, no_vcs_ignore=False, global=True)
[2023-04-11T13:03:46.615+0000] {process_utils.py:187} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-04-11T13:03:46.616+0000] {process_utils.py:187} INFO -     added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
[2023-04-11T13:03:46.619+0000] {process_utils.py:187} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-04-11T13:03:47.092+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv8vzl1bne/bin/pip install -r /tmp/venv8vzl1bne/requirements.txt
[2023-04-11T13:03:47.173+0000] {process_utils.py:183} INFO - Output:
[2023-04-11T13:03:59.885+0000] {process_utils.py:187} INFO - Collecting requests==2.25.1
[2023-04-11T13:04:04.197+0000] {process_utils.py:187} INFO -   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
[2023-04-11T13:04:04.421+0000] {process_utils.py:187} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 284.0 kB/s eta 0:00:00
[2023-04-11T13:04:04.523+0000] {process_utils.py:187} INFO - Requirement already satisfied: chardet<5,>=3.0.2 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv8vzl1bne/requirements.txt (line 1)) (4.0.0)
[2023-04-11T13:04:04.526+0000] {process_utils.py:187} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv8vzl1bne/requirements.txt (line 1)) (2022.12.7)
[2023-04-11T13:04:04.904+0000] {process_utils.py:187} INFO - Collecting idna<3,>=2.5
[2023-04-11T13:04:04.998+0000] {process_utils.py:187} INFO -   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
[2023-04-11T13:04:06.008+0000] {process_utils.py:187} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 57.5 kB/s eta 0:00:00
[2023-04-11T13:04:06.022+0000] {process_utils.py:187} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv8vzl1bne/requirements.txt (line 1)) (1.26.15)
[2023-04-11T13:04:28.023+0000] {process_utils.py:187} INFO - Installing collected packages: idna, requests
[2023-04-11T13:04:28.025+0000] {process_utils.py:187} INFO -   Attempting uninstall: idna
[2023-04-11T13:04:28.031+0000] {process_utils.py:187} INFO -     Found existing installation: idna 3.4
[2023-04-11T13:04:28.035+0000] {process_utils.py:187} INFO -     Not uninstalling idna at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venv8vzl1bne
[2023-04-11T13:04:28.036+0000] {process_utils.py:187} INFO -     Can't uninstall 'idna'. No files were found to uninstall.
[2023-04-11T13:04:28.226+0000] {process_utils.py:187} INFO -   Attempting uninstall: requests
[2023-04-11T13:04:28.231+0000] {process_utils.py:187} INFO -     Found existing installation: requests 2.28.2
[2023-04-11T13:04:28.233+0000] {process_utils.py:187} INFO -     Not uninstalling requests at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venv8vzl1bne
[2023-04-11T13:04:28.234+0000] {process_utils.py:187} INFO -     Can't uninstall 'requests'. No files were found to uninstall.
[2023-04-11T13:04:28.439+0000] {process_utils.py:187} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-04-11T13:04:28.441+0000] {process_utils.py:187} INFO - hvac 1.1.0 requires requests<3.0.0,>=2.27.1, but you have requests 2.25.1 which is incompatible.
[2023-04-11T13:04:28.442+0000] {process_utils.py:187} INFO - docker 6.0.1 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-11T13:04:28.443+0000] {process_utils.py:187} INFO - apache-***-providers-http 4.2.0 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-11T13:04:28.447+0000] {process_utils.py:187} INFO - Successfully installed idna-2.10 requests-2.25.1
[2023-04-11T13:04:29.815+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv8vzl1bne/bin/python /tmp/venv8vzl1bne/script.py /tmp/venv8vzl1bne/script.in /tmp/venv8vzl1bne/script.out /tmp/venv8vzl1bne/string_args.txt
[2023-04-11T13:04:29.832+0000] {process_utils.py:183} INFO - Output:
[2023-04-11T13:04:35.065+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-11T13:04:35.100+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=joke_collector, task_id=joke_collector_task, execution_date=20230411T130334, start_date=20230411T130338, end_date=20230411T130435
[2023-04-11T13:04:35.175+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-11T13:04:35.221+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
